name: Crawler Runner & del

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.CRAWLER }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Set locale
      run: |
        export LC_ALL=C.UTF-8
        export LANG=C.UTF-8

    - name: Run crawler script
      run: |
        cd node-sp
        python crawler.py

    - name: Encode output and save as config.txt
      run: |
        cd node-sp
        base64 -w 0 nodes.txt > ../config.txt

    - name: Commit and push changes
      run: |
        git config user.name "vampireisoves"
        git config user.email "893751627@qq.com"
        git add config.txt README.md
        git commit -m "Update config.txt and README.md with latest crawler output" || echo "No changes to commit"
        git push origin main
  del_runs:
    needs: run-crawler
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 4
